config/routes.rb
 Rails.application.routes.draw do
  

  get '/operazionis/index' => redirect('/')
	

  post 'users/new' => 'users#new'
  
  get 'conversaziones/new'
  patch '/conversaziones' => 'conversaziones#cancella_notifica_messaggi'
  post '/conversazione' => 'conversaziones#index'
  post '/conversaziones' => 'conversaziones#create'
  get 'conversaziones/index' => 'conversaziones#index'
  post '/conversaziones/index' => 'conversaziones#load_conversazione'
  patch '/conversaziones/index' => 'conversaziones#reload'
  post '/ratings' => 'ratings#create'
  post '/ratings/:id' => 'ratings#update'
  get 'preferitis/:id' => 'preferitis#destroy'
  patch '/notificas' => 'notificas#test'
  post '/preferitis' => 'preferitis#create'
  get 'operazionis/new'
  post '/operazionis' => 'operazionis#create'
  get 'operazionis/:id/edit' => 'operazionis#edit'
  patch 'operazionis/:id' => 'operazionis#update'
  delete 'operazionis/:id' => 'operazionis#destroy'
  
  get 'operazionis/:id' => 'operazionis#show'
  
  get 'scadenzes/index' =>redirect('/')
  get 'scadenzes/:id/edit' =>redirect('/')
  get 'scadenzes/edit' =>redirect('/')
  
  get 'officinas/new'
  get 'officinas/show'
  get 'officinas/edit'
  get 'officinas/index' =>'officinas#index'
  post '/officinas' => 'officinas#create'
  post '/officinas/:id' => 'officinas#setta_cortesia'
  delete 'officinas/:id' => 'officinas#destroy'
  patch 'officinas/:id' => 'officinas#update'
  get 'officinas/:id' => 'officinas#show'
  get 'officinas/:id/edit' => 'officinas#edit'

  get 'autoveicolos/edit'
  delete 'autoveicolos/:id' => 'autoveicolos#destroy'
  get 'autoveicolos/' => 'autoveicolos#index'
  get 'autoveicolos/show'
  get 'autoveicolo/show'
  get 'password_resets/new'
  get 'password_resets/edit'
 
  get 'contattaci' => 'pagina_statica#contattaci'
  get 'faq' => 'pagina_statica#faq'
  
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  


  resources :users, shallow: true
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :autoveicolos,   only: [:new, :create, :edit, :update, :show]
  resources :officinas, only: [:new]
  resources :scadenzes
  root                'pagina_statica#home'
  get '*missing' => redirect('/')
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  skip_before_action :verify_authenticity_token  

 
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Ti abbiamo inviato una email con le istruzioni per reimpostare la password."
      redirect_to root_url
    else
      flash.now[:danger] = "Indirizzo email non trovato."
      render 'new'
    end
  end
  def password_blank?
      params[:user][:password].blank?
    end
  def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  #update  nuova password 
  def update
    if password_blank?
      flash.now[:danger] = "Il campo password non può essere vuoto."
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "La password è stata reimpostata."
      redirect_to @user
    else
      render 'edit'
    end
  end
 #getter dell'user
  def get_user
      @user = User.find_by(email: params[:email])
    end
  
  
  def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end
  #link reset password expiration
  def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Il link non è più valido"
        redirect_to new_password_reset_url
    end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'  type='text/css'>
</head>
<div class="registrazione">
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      
      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <br/>
      <%= f.label :password_confirmation, "Conferma" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br/>
      <%= f.submit "Aggiorna Password", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>
</div>
</html>

app/views/password_resets/new.html.erb
<!DOCTYPE html>
      <html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'  type='text/css'>
</head>
<body>
<div class="registrazione">
<h1>Recupera Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="/password_resets" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="q4CymNk/cItapSYjl6Bzm7HCh7gimTbhB8wMtmWpoyZHDI4KJ0sRsTIa/W9RZ30DagO+YFB0DB31Qqqr8ve9cw==" />
      <label for="password_reset_email">Email</label>
      <input class="form-control" type="email" name="password_reset[email]" id="password_reset_email" />
      <br/>
      <input type="submit" name="commit" value="Invia" class="btn btn-primary btn-block" data-disable-with="Submit" />
</form>  </div>
</div>
</div>
</body>
</html>