config/routes.rb
 Rails.application.routes.draw do
  

  get '/operazionis/index' => redirect('/')
	

  post 'users/new' => 'users#new'
  
  get 'conversaziones/new'
  patch '/conversaziones' => 'conversaziones#cancella_notifica_messaggi'
  post '/conversazione' => 'conversaziones#index'
  post '/conversaziones' => 'conversaziones#create'
  get 'conversaziones/index' => 'conversaziones#index'
  post '/conversaziones/index' => 'conversaziones#load_conversazione'
  patch '/conversaziones/index' => 'conversaziones#reload'
  post '/ratings' => 'ratings#create'
  post '/ratings/:id' => 'ratings#update'
  get 'preferitis/:id' => 'preferitis#destroy'
  patch '/notificas' => 'notificas#test'
  post '/preferitis' => 'preferitis#create'
  get 'operazionis/new'
  post '/operazionis' => 'operazionis#create'
  get 'operazionis/:id/edit' => 'operazionis#edit'
  patch 'operazionis/:id' => 'operazionis#update'
  delete 'operazionis/:id' => 'operazionis#destroy'
  
  get 'operazionis/:id' => 'operazionis#show'
  
  get 'scadenzes/index' =>redirect('/')
  get 'scadenzes/:id/edit' =>redirect('/')
  get 'scadenzes/edit' =>redirect('/')
  
  get 'officinas/new'
  get 'officinas/show'
  get 'officinas/edit'
  get 'officinas/index' =>'officinas#index'
  post '/officinas' => 'officinas#create'
  post '/officinas/:id' => 'officinas#setta_cortesia'
  delete 'officinas/:id' => 'officinas#destroy'
  patch 'officinas/:id' => 'officinas#update'
  get 'officinas/:id' => 'officinas#show'
  get 'officinas/:id/edit' => 'officinas#edit'

  get 'autoveicolos/edit'
  delete 'autoveicolos/:id' => 'autoveicolos#destroy'
  get 'autoveicolos/' => 'autoveicolos#index'
  get 'autoveicolos/show'
  get 'autoveicolo/show'
  get 'password_resets/new'
  get 'password_resets/edit'
 
  get 'contattaci' => 'pagina_statica#contattaci'
  get 'faq' => 'pagina_statica#faq'
  
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  


  resources :users, shallow: true
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :autoveicolos,   only: [:new, :create, :edit, :update, :show]
  resources :officinas, only: [:new]
  resources :scadenzes
  root                'pagina_statica#home'
  get '*missing' => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if logged_in? %>
<html class="sfondo_senza_scritta">
<% else %>
<html class="sfondo">
<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'  type='text/css'>
<% end %>

    <script type="text/javascript">
    
    function test(input){
        var id = {'id': input}
        $.ajax({
        url: "/notificas",
        type: "PATCH",
        data: id
        });
}
</script>
  <head>
    <title>CarAdvisor</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    </head>
    <body class ="trasparente" >
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
        <a class="navbar-brand" href="https://car-advisors.herokuapp.com/" id="logo"><span class="glyphicon glyphicon-home"></span> CarAdvisor</a>
        </div>
     <ul class="nav navbar-nav navbar-right">
     <% if logged_in? %>
     
    
    
	  <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="logologin"><span class="glyphicon glyphicon-bell"></span> 
      
       <% if current_user.notificas.where(read: 'f').count==1 %>
         <%= current_user.notificas.where(read: 'f').count %> Notifica 
       <% else %>
         <%= current_user.notificas.where(read: 'f').count %> Notifiche
       <% end %>
       <b class="caret"></b></a> 
          <ul class="dropdown-menu">
            <% if current_user.notificas.where(read: 'f').count==0 %>
                  "Nessuna notifica"
            <% end %>
            <% @notifica.where(user_id: current_id, read: 'f').find_each do |notifica| %>
               <li><a href="https://car-advisors.herokuapp.com/<%=notifica.notified_by_id%>" onclick="test(<%= notifica.id %>)"><%= notifica.tipo %> </a></li>
            <% end %>
         </ul>
	</li>
	 <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="logologin"><span class="glyphicon glyphicon-user"></span> </span> Account <b class="caret"></b></a>
         <ul class="dropdown-menu">
		 <li>
	 <a href="https://car-advisors.herokuapp.com/users/<%= current_id %>">Profilo</a>
	 </li>
	 
           <li><%= link_to "Modifica dati", edit_user_path(current_user) %></li>
         <% if current_user.admin?  %>
		   <li><%= link_to "Pannello Admin", users_path %></li>
		 <% end %>
           <li class="divider"></li>
           <li><%= link_to "Log out", logout_path, method: "delete" %></li>
         </ul>
		</li>
	<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"id="logologin"><span class="glyphicon glyphicon-th-list"></span> Menù <b class="caret"></b></a>
            <ul class="dropdown-menu">
			  <li><%= link_to "I tuoi veicoli", "https://car-advisors.herokuapp.com/autoveicolos/" %></li>
              <li><%= link_to "Lista Officine", officinas_index_url %></li>
              <li><%= link_to "Messaggi", "https://car-advisors.herokuapp.com/conversaziones/index"  %></li>
			  <li><%= link_to "FAQ", faq_url %></li>
			  <li><%= link_to "Contattaci", contattaci_url %></li>
		  </ul>
    </li>
    <% else %>
            <li><a href="https://car-advisors.herokuapp.com/users/new" id="minilogo"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="https://car-advisors.herokuapp.com/login" id="minilogo"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <% end %>
           </ul>
    </div>
    </nav>
    <% flash.each do |message_type, message| %> <div class="container alert-<%= message_type %>"><br/><%= message %> <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </div> <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>